### ISSUE TITLE
Not working with Raspberry Pi2

### ISSUE THREAD

**Issue by koss822** [riyas-org/nrf24scannerPi#1]
It seems that it uses obsolete library bcm2835 which does not supports correctly Raspberry Pi2. I tested same PCB connected to Raspberry Pi B+ where it works correctly with Raspberry Pi 2 where it does not. On Raspberry Pi 2 I am able to use NRF24 without any issues in Python with pi-spydev module so connection and also settings with kernel and DT seems ok.

It must be issue with this appliacation.

**Comment by riyas-org** [comment]
Yes, it uses bcm2835 library. Will update (once i get time with  a new one). I had the same scanner  working with a python script but was too slow to scan.  thanks for the note

**Comment by LostXine** [comment]
After some searching I found a solution for Pi2 and my Pi3.
Edit bcm2835.h, change 
`#define BCM2835_PERI_BASE 0x20000000`
to
`#define BCM2835_PERI_BASE 0x3F000000`
Remember to rebuild bcm2835.so
Hope it helps.
Thank you all.
